services:
  frontend:
    build: ./frontend
    image: frontend:custom
    container_name: frontend
    networks: ["transcendence_network"]
    ports: "5500:5500"
    restart: always
# backend:
# 	build: ./backend
# 	image: backend:custom
# 	container_name: backend
# 	networks: ["transcendence_network"]
# 	restart: always
# nginx:
# 	depends_on:
# 	frontend:
# 		condition: service_healthy
# 	build: ./nginx
# 	image: nginx:custom
# 	container_name: nginx
# 	networks: ["transcendence_network"]
# 	ports: ["443:443"]
# 	restart: always

networks:
  transcendence_network:
    name: transcendence_network
