events {
}

http {
	access_log /dev/stdout;
	error_log /dev/stderr warn;
	
	server	{
	# Port listened to by NGINX (HTTPS).
	# Hostname handled by this server block.
		listen	8888 ssl;

	# Allow only these TSL/SSL protocols.
		ssl_protocols	TLSv1.2 TLSv1.3;
	
	# Path to the SSL private key and certificate.
		ssl_certificate_key	/etc/nginx/ssl/server.key;
		ssl_certificate	/etc/nginx/ssl/server.crt;

	# Frontend (SvelteKit).
		location / {
			proxy_pass	http://frontend:5500;
			# proxy_http_version	1.1;

             proxy_set_header Host localhost:5500;
             proxy_set_header X-Real-IP $remote_addr;
		}

	# Backend (Express).
		location /api/ {
			proxy_pass	http://backend:3000;
			# proxy_http_version	1.1;

            # proxy_set_header Host $host;
            # proxy_set_header X-Real-IP $remote_addr;
		}

	# Backend (to upload profile avatar).
		location /uploads/ {
			proxy_pass http://backend:3000;
		}
		
	}
}
